### ISSUE TITLE
Config path change

### ISSUE THREAD

**Issue by kted** [mainsail-crew/moonraker-timelapse#82] opened 2022-12-09 08:03 UTC
The configuration path of klipper now is  "${HOME}/printer_data/config" instead of  "${HOME}/klipper_config" as defined in install.sh.
So the installation fails.
If I change the path manually, I get a "Dirty" warning in update manager, and trying to fix it reverts to the old path.
Please update with the new requirements

![image](https://user-images.githubusercontent.com/21242761/206654610-feb8e76b-8ecb-4a2c-b4c4-6f3098b32183.png)

**Comment by FrYakaTKoP** [comment] 2022-12-16 00:15
duplicate of #71 

sorry had time to fix the installer yet, try to resolve it next couple days.

close because duplicate.

**Closed by FrYakaTKoP** 2022-12-16 00:15 UTC
